API_V1_PREFIX = "/api/v1"

ADMIN_PREFIX = f"{API_V1_PREFIX}/admin"
GAME_PREFIX = f"{API_V1_PREFIX}/game"
USER_PREFIX = f"{API_V1_PREFIX}/user"
SYSTEM_PREFIX = f"{API_V1_PREFIX}/system"
POKEMON_PREFIX = f"{API_V1_PREFIX}/pokemon"
GAME_TRAINER_PREFIX = f"{GAME_PREFIX}/trainer"
