API_V1_PREFIX = "/api/v1"

ADMIN_PREFIX = f"{API_V1_PREFIX}/admin"
GAME_PREFIX = f"{API_V1_PREFIX}/game"
USER_PREFIX = f"{API_V1_PREFIX}/user"
SYSTEM_PREFIX = f"{API_V1_PREFIX}/system"

ADMIN_TRAINER_PREFIX = f"{ADMIN_PREFIX}/trainers"
GAME_TRAINER_PREFIX = f"{GAME_PREFIX}/trainer"
