"""add official_artwork_url to pokemons

Revision ID: d7caf62b9e45
Revises: c3e8d5a0f1b2
Create Date: 2026-06-19 19:56:08.416862

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7caf62b9e45"
down_revision: Union[str, None] = "c3e8d5a0f1b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trainers_email", table_name="trainers")
    op.drop_index("ix_trainers_id", table_name="trainers")
    op.drop_index("ix_trainers_username", table_name="trainers")
    op.drop_table("trainers")
    op.add_column(
        "pokemons",
        sa.Column("official_artwork_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemons", "official_artwork_url")
    op.create_table(
        "trainers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="trainers_pkey"),
    )
    op.create_index("ix_trainers_username", "trainers", ["username"], unique=True)
    op.create_index("ix_trainers_id", "trainers", ["id"], unique=False)
    op.create_index("ix_trainers_email", "trainers", ["email"], unique=True)
    # ### end Alembic commands ###
